baseURL = "https://s1r1us.ninja"
languageCode = "en-us"
title = "s1r1us Blog"
theme = "cactus"
copyright = "Copyright © s1r1us" # cactus will use title if copyright is not set
disqusShortname = "s1r1us" # Used when comments is enabled. Cactus will use site title if not set
[services.googleAnalytics]
# googleAnalytics = "G-GZC3570SFD"
disableKinds = ["taxonomy", "taxonomyTerm"]


# summaryLength = 2


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 1
    ordered = false
    startLevel = 1
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "monokai"
    tabWidth = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  colortheme = "light" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  # googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default
  css = ["css/custom.css"]
  # Home page settings
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/msrkp" # title link for projects list

 dateFormat = "2006-01-02" # default
[[params.social]]
  name = "github"
  link = "https://github.com/msrkp"
[[params.social]]
  name = "email"
  link = "l33tsirius@gmail.com" 
[[params.social]]
  name = "twitter"
  link = "https://twitter.com/s1r1u5_"

